print('🔍 Final MongoDB Verification')
print('=' * 30)
from app import test_mongodb_connection
success, message = test_mongodb_connection()
print('Direct Connection:', 'SUCCESS' if success else 'FAILED')
print('Message:', message)
print()
print('📊 Summary:')
print('- MongoDB packages installed')
print('- Connection string updated')
print('- Authentication working')
print('- Database access confirmed')
print('- Test operations successful')
print()
if success:
    print('🎉 MongoDB integration is fully working!')
    print('Your app will now save search results to MongoDB')
    print('Fallback to file storage if MongoDB fails')
else:
    print('❌ MongoDB connection still has issues')
